version: "3.8"

services:
  db:
    container_name: rpgmypet_db
    build:
      context: ./internal/databases
      dockerfile: .
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  
  server:
    container_name: rpgmypet_server
    build:
      context: .
      dockerfile: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENVIRONMENT=${APP_ENVIRONMENT}
      - APP_PORT=${APP_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db